[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

# Install dependencies from netlify/functions/package.json
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Redirect for function endpoints
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
